#!/usr/bin/env bash

rofi -modi drun \
-lines 10 \
-columns 3 \
-padding 10 \
-width 70 \
-scroll-method 1 \
-show drun &

if [[ pgrep -x compton ]]; then
  source ~/.commands/rofi-widget/find-rofi
  transset -i $win_id 1
fi
