#!/bin/bash

sudo apt install lightdm-gtk-greeter-settings # install lightdm
sudo apt install openbox # install wm

# Firmware
sudo apt install firmware-linux firmware-linux-free firmware-linux-nonfree firmware-atheros firmware-amd-graphics firmware-realtek intel-microcode

# Utility
sudo apt install --no-install-recommends thunar
sudo apt install gvfs-backends gvfs-fuse thunar-archive-plugin tumbler-plugins-extra ffmpeg catfish
sudo apt install feh evince mpv imagemagick font-manager gimp inkscape
