#!/bin/bash

while : ; do  # Do infinite while loop
wget --spider --quiet http://google.com

if [[ "$?" == 0 ]]; then # if there internet connection do
  # Manage dotfiles with yadm
  yadm add ~/.commands
  yadm rm -r --cached ~/.commands/thegen/tint2/
  yadm rm --cached ~/.commands/thegen/tint2rc
  yadm add ~/.tmux.conf
  yadm add ~/.zshrc
  yadm add ~/.config/zsh
  yadm add ~/.config/openbox
  yadm add ~/.config/rofi
  yadm add ~/.config/Thunar
  yadm add ~/.config/polybar
  yadm add ~/.config/jgmenu
  yadm rm -r --cached ~/.config/jgmenu/backup
  yadm add ~/.config/xfce4/xfconf/xfce-perchannel-xml
  yadm commit -m "daily commit"
  yadm push -u origin master

  # Manage neovim config
  cd ~/.config/nvim/
  git add -A
  git commit -m "daily commit"
  git push -u origin master

  break # Stop infinite while loop
fi
sleep 20
done
