#!/bin/bash
while true
do
  DATETIME=`date`
  BATTERYSTATE=$( acpi -b | awk '{ split($5,a,":"); print substr($3,0,2), $4, "["a[1]":"a[2]"]" }' | tr -d ',' )
  xsetroot -name "${DATETIME} ${BATTERYSTATE}"
  sleep 1m
done
