#! /bin/sh

sxhkd &
~/.fehbg &
xset +fp ~/.local/share/fonts/misc
conky -c ~/.config/conky/lemonbar/sakura | lemonbar -p -f "-*-rissole-*" -f "-*-waffle-*" -g x28 -B "#FAE2F7" -F "#141c21" | dash &
lxpolkit &

bspc monitor -d I II III IV V 

bspc config border_width         2
bspc config window_gap          12
bspc config bottom_padding       4
bspc config top_padding         32
bspc config left_padding         4
bspc config right_padding        4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a gcolor3 state=floating follow=on
bspc rule -a mpv state=floating follow=on
bspc rule -a Screenkey manage=off
