#!/bin/bash

# Delete LICENSE file
echo "Remove junk files"
rm ~/LICENSE ~/README.md

# Clone repos
echo "Clone other repositories"
git clone git@github.com:ekickx/Uzuki-MPV.git
mkdir -p ~/App/builds/; cd ~/App/builds
git clone git@github.com:ekickx/sss.git

# Install tmux plugins
echo "Setting up tmux"
tmux source ~/.tmux.conf

# Set up neovim
echo "Setting up neovim"
nvim +PlugInstall +qall > /dev/null

# Set up MPV
echo "Setting up mpv"
~/.config/mpv/init.sh > /dev/null
